09-12-2019 02:41:25 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-12-2019 02:41:25 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
