09-12-2019 02:41:25 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-12-2019 02:41:25 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:21:19 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:21:19 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:23:16 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:23:16 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:29:24 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:29:24 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:32:22 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:32:22 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:34:04 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:34:04 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:51:33 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:51:33 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:54:46 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:54:46 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
09-13-2019 12:59:50 PM :ERROR: Filename: test_custom_logger.py: Line: 63; test failed
NoneType: None
09-13-2019 12:59:50 PM :INFO: Filename: test_custom_logger.py: Line: 64; OTC-231.3 PASSED
